version: '3.3'

networks:
  core: {}

  
services:
  core:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
      - core
      
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    networks:
      - core
    
